---
    name: Prettier
    # Runs and writes the results of prettier to changed files
    # Only runs when changes happen to main
    
    on:
        pull_request_target:
            branches:
                - main
    
    permissions:
      checks: write
      contents: write
    
    jobs:
        prettier:
            runs-on: ubuntu-latest
    
            steps:
                - name: Checkout
                  uses: actions/checkout@v4
                  with:
                      # Make sure the actual branch is checked out when running on pull requests
                      ref: ${{ github.head_ref }}
                
                - name: Install prettier
                  run: npm install prettier
    
                - name: Run prettier              
                  uses: wearerequired/lint-action@v2.3.0
                  with:
                    prettier: true
                    prettier_args: "**/*.{ts,json,css,scss,md}"